# Generated by Django 5.0.3 on 2024-03-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_belongs_group_alter_belongs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='belongs',
            name='role',
            field=models.CharField(choices=[('Leader', 'Leader'), ('Member', 'Member')], default='Member', max_length=10),
        ),
    ]
