# Generated by Django 5.0.1 on 2024-03-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'Todo'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='To Do', max_length=12),
        ),
    ]
